# sample code
POST https://"YOUR AZURE CONTENT SAFETY ENDPOINT"contentsafety/text:analyze?api-version=2023-04-30-preview
Host: "YOUR AZURE CONTENT SAFETY ENDPOINT"
Content-Type: application/json
Ocp-Apim-Subscription-Key: "YOUR AZURE CONTENT SAFETY API KEY"

{
 "text": "We are planning a meeting at our Saitama office.",
 "categories": [
 "Hate","Sexual","SelfHarm","Violence"
 ],
 "blocklistNames": [
 "sample"
 ],
 "breakByBlocklists": false
}