# -*- coding: utf-8 -*-
"""Playground_Copywriter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nAteyrE-mPI-dfTEGek0OFFH7dRQtk96
"""

# openaiライブラリのインストール
!pip install openai==0.28.1

import os
# APIキーを環境変数に登録する（現在のセッションに一時的に保存）
os.environ['OPENAI_API_KEY'] = 'ここにAPIキーの値を入力してください'

# 登録した環境変数の値を確認する
print(os.environ['OPENAI_API_KEY'])

#Note: The openai-python library support for Azure OpenAI is in preview.
import os
import openai
openai.api_type = "azure"
openai.api_base = "<OPENAI_ENDPOINT>" # エンドポイントを指定
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.ChatCompletion.create(
  engine="OPENAI_DEPLOYMENT", # モデルのデプロイ名を指定
  messages = [
      {"role":"system",
       "content":"## 役割\nあなたは優秀なコピーライターです。ユーザーが提供するお題に対してのコピーを考えてください。\n## 制約条件\n・コピーは20文字以内です。\n・漢字の割合を30％、ひらがなの割合を70％にします。\n・魅力的且つ印象的なコピーを考えてください。"},
      {"role":"user",
       "content":"ゆず味のアイスキャンディー"},
      {"role":"assistant",
       "content":"\"爽やかなゆずの口どけ\""},
      {"role":"user",
       "content":"日向夏のアイスキャンディー"},
      {"role":"assistant",
       "content":"\"夏の陽射しを凍らせた至福\""},
      {"role":"user",
       "content":"もう少し砕けた表現にしてください。"},
      {"role":"assistant",
       "content":"\"まろやかビター、元気の出る夏味\""},
      # 新しいキャッチコピーの依頼を追加
      {"role":"user",
       "content":"\"鯖味のソフトクリーム\""}
      ],
  temperature=1,
  max_tokens=800,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None)

print(response["choices"][0]["message"]["content"]) # 結果を出力する